# specifique au local pour le nginx - pour la prod c'est lt-proxy-letncryt
server {
    listen 80;
    server_name _;

    # --- AUGMENTER LA TAILLE MAX DES FICHIERS ---
    client_max_body_size 100M; 

    # 1. ROUTAGE API BLOG (Pour le Dashboard local)
    location /api/blog/ {
        proxy_pass http://blog-backend:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. REDIRECTION API PRINCIPALE
    location /api {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 3. IMAGES
    location /uploads {
        proxy_pass http://backend:3000;
    }

    # 4. APP PRINCIPALE
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }
}
